### ISSUE TITLE
Transfer repo to twikoojs org

### ISSUE THREAD

**Issue by imaegoo** [twikoojs/twikoo-cloudflare#4]
> [ChaiByte](https://github.com/ChaiByte) commented [yesterday](https://github.com/twikoojs/twikoo-cloudflare/pull/1#issuecomment-2164302312)
> It seems unnecessary to fork a new branch to exist independently, which would affect version synchronization. Consider migrating the original project to the organization, or the author could serve as the maintainer of the official forked version for subsequent development.
> 
> [Tao-VanJS](https://github.com/Tao-VanJS) commented [20 hours ago](https://github.com/twikoojs/twikoo-cloudflare/pull/1#issuecomment-2164355017)
> Hi @ChaiByte,
> 
> I don't fully understand what you meant. Are there any specific actions you suggest me to do?
> 
> [ChaiByte](https://github.com/ChaiByte) commented [18 hours ago](https://github.com/twikoojs/twikoo-cloudflare/pull/1#issuecomment-2164618746)
> 
> I have envisioned a workflow, which is to directly set you as a collaborator of the twikoo-cloudflare repository. This way, you can directly obtain the permission to push new branches to twikoo-cloudflare without having to consider the complex upstream and downstream relationships between the two repositories. In fact, it might be that I am overthinking it.
> 
> From: Tao-VanJS:main -> twikoojs:main
> To: twikoojs:feat-xxx -> twikoojs:main
> I mistakenly introduced a strong assumption that you might be the long-term maintainer.
> 
> The reason for my confusion is that I am currently using R2 and came across your project, which is very useful. However, I noticed that your main branch is more up-to-date than the official fork, so for a moment, I was unclear about the collaboration method you are using. Perhaps I just need to focus on the official fork version, right?
> 
> [Tao-VanJS](https://github.com/Tao-VanJS) commented [9 hours ago](https://github.com/twikoojs/twikoo-cloudflare/pull/1#issuecomment-2166038284)
> Hi @ChaiByte,
> 
> I'm not the long-term maintainer of the twikoo project. I'm a user of twikoo, but I found that the existing cloud deployments of twikoo had the issues of long cold-start time (it takes about 6s to initially load the comments if the site hasn't been visited for a while). So I built the Cloudflare-based solution, which reduced the cold-start time to 0.5s thanks to the seamless integration between Cloudflare workers and D1. After building my solution I told the maintainer of twikoo - @imaegoo: feel free to take my code to the twikoo project. I don't mind if the maintainer puts my code into the main repo: https://github.com/twikoojs/twikoo, or creates a separate repo for it. It's the maintainer's decision. This is why you're seeing the situation as it is.
> 
> Some GitHub user went to my clone of the repo and provided some feedback, I addressed the feedback in my repo and created this PR to patch into the official repo of twikoo-cloudflare.

@Tao-VanJS 

I agree with merging the two repositories to avoid pulling code manually.

1. Delete `twikoojs/twikoo-cloudflare` repo
2. Transfer `Tao-VanJS/twikoo-cloudflare` to `twikoojs/twikoo-cloudflare`, after that, user who access `Tao-VanJS/twikoo-cloudflare` will automatically redirect to `twikoojs/twikoo-cloudflare`
3. Add @Tao-VanJS to `twikoojs/twikoo-cloudflare` maintainers list

If you are ready, I will invite you to `twikoojs` organization so you can transfer the repo.

**Thank you for your contribution!**

**Comment by 0xMashiro** [comment]
[Transferring a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) might need maintainer (Tao) as member of `twikoojs` org. I think you can try this:

1. For Tao: Make `Tao-VanJS/twikoo-cloudflare` archived, see [Archiving repositories](https://docs.github.com/en/repositories/archiving-a-github-repository/archiving-repositories). 
  - update readme telling users how to reach the official one. 
  - DO NOT DELETE IT DIRECTLY if you have not backed it up.
2. For twikoojs: Keep developing on `twikoojs/twikoo-cloudflare`, [add Tao as outside collaborator to twikoo-cloudflare](https://docs.github.com/organizations/managing-user-access-to-your-organizations-repositories/adding-outside-collaborators-to-repositories-in-your-organization)
4. If Tao hope to be a long-term maintainer in the future, then [Converting an outside collaborator to an organization member](https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-outside-collaborators/converting-an-outside-collaborator-to-an-organization-member)

If you prefer to merge other branches (like feat/xxx, doc/xxx) into the main branch after reviewing pull requests, rather than developing directly on the main branch, consider setting up a [branch protection rule](vscode-file://vscode-app/d:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-sandbox/workbench/workbench.html) for the main branch. This is a good practice, but it's not necessary in every case.

**Comment by Tao-VanJS** [comment]
> If you are ready, I will invite you to twikoojs organization so you can transfer the repo.

Yes. I'm ready to transfer.

**Comment by Tao-VanJS** [comment]
Transfer completed
